// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMqet9TJ4sXcxkB1Mm6VVthvkjzau_saI',
    appId: '1:123960965445:web:a599553694a51581d3662c',
    messagingSenderId: '123960965445',
    projectId: 'crud-operations-c0211',
    authDomain: 'crud-operations-c0211.firebaseapp.com',
    storageBucket: 'crud-operations-c0211.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTdtiCFXeLGwJcUim_iygtlsnaIuSDS2E',
    appId: '1:123960965445:android:811118c56dd52a55d3662c',
    messagingSenderId: '123960965445',
    projectId: 'crud-operations-c0211',
    storageBucket: 'crud-operations-c0211.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNMROJOEv7AJCFcllJRvSkwj6n971hRg8',
    appId: '1:123960965445:ios:9b30326920c8967ad3662c',
    messagingSenderId: '123960965445',
    projectId: 'crud-operations-c0211',
    storageBucket: 'crud-operations-c0211.appspot.com',
    iosBundleId: 'com.example.crudOperations',
  );
}
